### ISSUE TITLE
Pretrained weight and Sparse RCNN implementation

### ISSUE THREAD

**Issue by bamps53** [PeizeSun/OneNet#14]
Thanks for sharing interesting and stimulating work!
Are you planning to release R50_nodcn and R50_dcn pretrained weight?
And in the paper you applied OneNet style label assignment on DETR and SparseRCNN. Are you also planning these implementation?

**Comment by enjoyyi00** [comment]
recently we have improved the model performance of R50_nodcn and R50_dcn.
we will release the model as soon as possible

**Comment by bamps53** [comment]
Thanks for the answer, I can't wait to try it.
