### ISSUE TITLE
Cost and loss difference

### ISSUE THREAD

**Issue by zaphodbbrx** [PeizeSun/OneNet#15]
Hello, could you please clarify something regarding loss computation. I understand that targets are assigned to net outputs based on their cost function computed as  focal_loss + giou_loss + l1_loss. But doesn't the cost value for these locations equal their loss value since loss is as well computed as sum of focal, l1 and giou components?

**Comment by PeizeSun** [comment]
Hi~
Yep, cost and loss is essentially the same.

**Comment by zaphodbbrx** [comment]
Thank you
