### ISSUE TITLE
What differences between min cost assignment in OneNet and Hungarian algorithm in Sparse R-CNN?

### ISSUE THREAD

**Issue by Mingfeng-Wang** [PeizeSun/OneNet#16]
It looks like pretty similar, used for replacing NMS post-processing.

**Comment by PeizeSun** [comment]
Hi~
Their functions are the same, while MinCost is a fast implementation of Hungarian algorithm. We will discuss them in revision of paper.

**Comment by Mingfeng-Wang** [comment]
@PeizeSun 
Yep, when I read the Sparse RCNN source code and found it could be better(same way as you). Maybe you could update Sparse RCNN?
