### ISSUE TITLE
Setting of learning rate

### ISSUE THREAD

**Issue by 0-LL-0** [PeizeSun/OneNet#18]
Why is the learning rate set so small? What happens if the learning rate is adjusted larger, such as 0.01 or 0.001?

**Comment by enjoyyi00** [comment]
because of the adam optimizer, the learning rate is smaller, the network will not coverge if the learning rate is adjusted larger, such as 0.01 or 0.001?

**Comment by 0-LL-0** [comment]
OK, got it. Thanks bro.
