### ISSUE TITLE
It seems that there is a typo in table 5 .

### ISSUE THREAD

**Issue by developer0hye** [PeizeSun/OneNet#21]
![image](https://user-images.githubusercontent.com/35001605/111553672-36f27380-87c8-11eb-89af-d3efac294884.png)

APs is too high. Is it typo?

**Comment by enjoyyi00** [comment]
yes，thanks for your kindly remind, we will fix this typo in recent version

**Comment by developer0hye** [comment]
@iFighting 
Thanks for your reply!
