### ISSUE TITLE
Questions about focal loss used, with comparison to CenterNet

### ISSUE THREAD

**Issue by shuuchen** [PeizeSun/OneNet#24]
Hi,

Thank you for your work.
I just have a question about the differences in focal loss used between OneNet and other previous works.
In CenterNet, the author used per-channel logistic regression with focal loss for key-point detection just like your code. 
The only difference seems to be the key-point positions selected for labeling, without Gaussian pre-processing.

Am I right ? Thanks.

**Comment by PeizeSun** [comment]
Hi~
The main difference of OneNet and CenterNet are:
(1) As you mentions, OneNet is labeling without Gaussian pre-processing.
(2)  CenterNet labels the positive sample as the feature point closest to center of gt box (only location cost), OneNet labels the positive samples by MinCost(sum of classification cost and location cost).

**Comment by shuuchen** [comment]
Hi,

Thank you. I see that in Fig. 5 of your paper. 
Sorry that I am still unclear about that 

> OneNet labels the positive samples by MinCost(sum of classification cost and location cost).

because you should prepare the positive samples before getting MinCost.

Since your positive samples are more discriminative than center of gt box, how did you decide their positions?
Did you used technical methods like attention map, or just labeled them by human decisions ?

**Comment by PeizeSun** [comment]
> Hi,
> 
> Thank you. I see that in Fig. 5 of your paper.
> Sorry that I am still unclear about that
> 
> > OneNet labels the positive samples by MinCost(sum of classification cost and location cost).
> 
> because you should prepare the positive samples before getting MinCost.
> 
> Since your positive samples are more discriminative than center of gt box, how did you decide their positions?
> Did you used technical methods like attention map, or just labeled them by human decisions ?

The positive samples are decided by MinCost, instead of human annotations.

**Comment by shuuchen** [comment]
Hi,
I still cannot understand how to calculate the sum of classification cost and location cost of each pixel ?
