### ISSUE TITLE
Why change the matcher from Minimum Cost to Hungarian?

### ISSUE THREAD

**Issue by superaha** [PeizeSun/OneNet#25]
As shown in the latest code at:
https://github.com/PeizeSun/OneNet/blob/e63c0cb8ac4a7275a0eea255184acb8d46a4c829/projects/OneNet/onenet/detector.py#L24

The matcher is changed from Minimum Cost at OneNet to Hungarian Matcher. What's the performance gap between this two matchers? Is this change to make the code compatible with the Paper " What Makes for End-to-End Object Detection?"?

I did not see any the details in the paper "What Makes for End-to-End Object Detection?" of which matcher is used in the experiments.

Thanks!

**Comment by PeizeSun** [comment]
Hi~
We find that MinCost is one special solution of Hungarian Matcher. (If there is no sample conflict, these two methods provide the same assignment).
![image](https://user-images.githubusercontent.com/40374966/125150359-d372c400-e171-11eb-8c4f-832cc2a8d102.png)

Also,  we find these two methods obtain basically the same performance.
![image](https://user-images.githubusercontent.com/40374966/125150326-8262d000-e171-11eb-81e5-d165c3c7824a.png)

**Comment by superaha** [comment]
Thank you. That makes sense.
