### ISSUE TITLE
where are the multi-head training implement?

### ISSUE THREAD

**Issue by lzymmm123** [PeizeSun/OneNet#29]
## ❓ where are the multi-head training implement?
Thanks for your great work!
After I traverse all code, I have not found  code about multi-head training in this project.
Am I ignoring something important?
![2022-01-25-162628_520x435_scrot](https://user-images.githubusercontent.com/34116341/150939696-b33d4e75-886e-4564-9a21-ec54a2a8d53c.png)

**Comment by PeizeSun** [comment]
Hi~
We remove the multi-head training and its implementation is discarded.

**Comment by lzymmm123** [comment]
oh, I see. Thanks.
