### ISSUE TITLE
a question about select the topk bboxes as final result?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [PeizeSun/OneNet#7]
hi @PeizeSun 
i have a question, why first select the topk bboxes for per class and then select the topk bboxes as final result among those from all classes (k * topk) (see the [link](https://github.com/PeizeSun/OneNet/blob/40e962446d/projects/OneNet/onenet/detector.py#L183-L188)), instead of directly select the topk bboxes for all classes?

**Comment by PeizeSun** [comment]
Hi~
Directly select the topk bboxes for all classes would cause a cuda error. Maybe H*W*K is too big.
