### ISSUE TITLE
windows平台下能使用吗？

### ISSUE THREAD

**Issue by ZZHHogan** [PeizeSun/OneNet#8]
请问在windows平台下能使用吗？README中没有提及win系统

**Comment by huangluyao** [comment]
我在windows编译报错
error: member "torch::jit::ProfileOptionalOp::Kind" may not be initialized

**Comment by enjoyyi00** [comment]
> 我在windows编译报错
> error: member "torch::jit::ProfileOptionalOp::Kind" may not be initialized

detectron2 and onenet can not to be installed in windows currently
