### ISSUE TITLE
some issue in loss.py

### ISSUE THREAD

**Issue by LamHoCN** [PeizeSun/OneNet#9]
def _get_src_permutation_idx(self, indices):
      
        # permute predictions following indices 
        batch_idx = torch.cat([torch.full_like(src, i) for i, (src, _) in enumerate(indices)])
        src_idx = torch.cat([src for (src, _) in indices])
        return batch_idx, src_idx

    def _get_tgt_permutation_idx(self, indices):
        # permute targets following indices
        batch_idx = torch.cat([torch.full_like(tgt, i) for i, (_, tgt) in enumerate(indices)])
        tgt_idx = torch.cat([tgt for (_, tgt) in indices])
        return batch_idx, tgt_idx

if src or tgt is an empty tensor, it will cause an error :
in _get_src_permutation_idx
    src_idx = torch.cat([src for (src, _) in indices])
RuntimeError: All input tensors must be on the same device. Received cpu and cuda:0
i and src are shown below:
0 tensor([ 1943, 20287, 17785,  4497,  6055], device='cuda:0')
1 tensor([11828,  6450, 13916,  5106], device='cuda:0')
2 tensor([14112, 14121,  5737, 12050, 12050, 13194,  9346,  9346,  5709,  3606,
         8618, 12050,  4386,  1322,  4027,  8988,  4348,  8220,  6483],
       device='cuda:0')
3 tensor([], dtype=torch.int64)
4 tensor([12109, 14215, 12786,  3532,  9812,  7320, 11715, 13564, 12183, 11136,
         7112,  9891,  6351, 11333, 11330, 15892, 12598, 12108, 11612,  8574,
         9881,  9521, 10388, 10374], device='cuda:0')
5 tensor([ 5141, 17595,  4841, 10382], device='cuda:0')
6 tensor([19832, 19286, 12812, 12812, 10720], device='cuda:0')

the third tensor is empty 

maybe it can be fixed by:

    def _get_src_permutation_idx(self, indices):
      
        # permute predictions following indices 
        batch_idx = torch.cat([torch.full_like(src, i) for i, (src, _) in enumerate(indices) if len(src)])
        src_idx = torch.cat([src for (src, _) in indices if len(src)])
        return batch_idx, src_idx

    def _get_tgt_permutation_idx(self, indices):
        # permute targets following indices
        batch_idx = torch.cat([torch.full_like(tgt, i) for i, (_, tgt) in enumerate(indices) if len(tgt)])
        tgt_idx = torch.cat([tgt for (_, tgt) in indices] if len(tgt))
        return batch_idx, tgt_idx

**Comment by LamHoCN** [comment]
by the way, this error caused in pytorch 1.7.0

**Comment by sephirothhua** [comment]
I got the same error in pytorch 1.7.0.

**Comment by PeizeSun** [comment]
Hi @LamHoCN @sephirothhua 
Is this error happening when running our code directly without any change?

**Comment by sephirothhua** [comment]
Yep @PeizeSun.

**Comment by qingquana** [comment]
I got the same error in pytorch 1.7.0.

**Comment by qingquana** [comment]
RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CPU, CUDA, QuantizedCPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

**Comment by PeizeSun** [comment]
Hi~@LamHoCN @sephirothhua @qingquana 
Thanks all for debugging.  

I reproduce this bug in Pytorch 1.7 and fix it by [here](https://github.com/PeizeSun/OneNet/blob/main/projects/OneNet/onenet/loss.py#L223)
